import atexit
import os
import time
import uuid
import warnings
import multiprocessing
import multiprocessing.util  # noqa: F401 -- registers multiprocessing's exit handler first, so ours runs before it
from multiprocessing import Process, freeze_support
from multiprocessing.managers import SyncManager
from threading import Thread
import pathlib

from sensor_core.data import DataManager
from sensor_core.memory.strg_manager import StorageManager
from sensor_core.dsp.dsp_manager import DSPManager
from sensor_core.memory.mem_utils import *
from sensor_core.memory.ring_adapter import unlink_ring
from sensor_core.utils.utils import *
from sensor_core.utils.utils import _coerce

# SensorManagers that have not been closed yet; any still open at interpreter exit are closed then
_OPEN_MANAGERS = {}


def _close_open_managers():
    for manager in list(_OPEN_MANAGERS.values()):
        try:
            manager.close()
        except Exception:
            pass


atexit.register(_close_open_managers)


def _track_shared_memory(name: str):
    """ Have Python's resource tracker remove the ring if this process exits without closing it
    (POSIX only; Windows frees shared memory when its last handle closes)
    """
    if os.name == "posix":
        try:
            from multiprocessing import resource_tracker
            resource_tracker.register(name, "shared_memory")
        except Exception:
            pass


def _untrack_shared_memory(name: str):
    if os.name == "posix":
        try:
            from multiprocessing import resource_tracker
            resource_tracker.unregister(name, "shared_memory")
        except Exception:
            pass


def _exit_with_parent():
    """ Runs in the metrics server process: exit when the process that owns the SensorManager dies, so a
    killed notebook kernel does not leave the server (and, through it, the shared memory) behind
    """
    parent = multiprocessing.parent_process()
    if parent is not None:
        Thread(target=lambda: (parent.join(), os._exit(0)), daemon=True).start()


def _join(worker, timeout: float) -> bool:
    """ Wait for a started Process or Thread; terminate a Process that does not finish in time
    :return: True if the worker finished (or was never started)
    """
    if isinstance(worker, Thread):
        if worker.ident is not None:
            worker.join(timeout)
        return not worker.is_alive()
    if worker.pid is None:
        return True
    worker.join(timeout)
    if worker.is_alive():
        worker.terminate()
        worker.join(5)
        return False
    return True


class SensorManager(DataManager, StorageManager):
    def __init__(self,
                 ser_channel_key: Union[np.ndarray, str],
                 commport: str,
                 baudrate: int = 115200,
                 dtype=np.float32,
                 data_mode: str = "line",
                 frame_shape: tuple = (1000, 100, 3),
                 fast_stream_path_a: str = None,
                 fast_stream_path_b: str = None,
                 start_stream_ingest: bool = False,
                 sqlite_path: str = "./serial_db.sqlite3",
                 rotate_frames: int = 8192,
                 rotate_seconds: float = 5.0,
                 stream_dir: str = None,
                 ring_capacity: int = 4096,
                 shm_name: str = None,
                 **kwargs):
        """ Initialize SensorManager Class
        Initializes serial port, shared memory object, and kwarg dictionary (args_dict).
        Call close() when finished, or use `with SensorManager(...) as sm:`, to stop the worker
        processes, store everything acquired, and release the shared memory.
        :param ser_channel_key: list of serial channel names
        :param commport: target serial port
        :param baudrate: target data transfer rate (in bits/sec)
        :param dtype: data type to store in shared memory object
        :param data_mode: 'line' or 'image'
        :param frame_shape: for line data, tuple of (num_points, window_size, num_channels); for image data, tuple of (height, width, num_channels)
        :param start_stream_ingest: if True, store acquired data: frames stream to segment files in stream_dir and are ingested into sqlite_path
        :param sqlite_path: SQLite database for stored data
        :param rotate_frames: seal a stream segment after this many frames
        :param rotate_seconds: seal a stream segment after this many seconds
        :param stream_dir: directory for stream segments; defaults to a folder named after sqlite_path
        :param ring_capacity: number of frames the shared-memory ring buffer holds
        :param shm_name: name of the shared-memory ring buffer; a unique name is generated by default
        :param fast_stream_path_a: deprecated and ignored; use stream_dir
        :param fast_stream_path_b: deprecated and ignored; use stream_dir
        """
        self._closed = True  # nothing to release until construction succeeds
        self._stopped = False
        self.dtype = dtype
        self.data_mode = data_mode
        if fast_stream_path_a is not None or fast_stream_path_b is not None:
            warnings.warn("fast_stream_path_a and fast_stream_path_b are no longer used; "
                          "stream files are written to stream_dir", DeprecationWarning, stacklevel=2)

        # Defines start method for multiprocessing. Necessary for windows and macOS
        self.os_flag = setup_process_start_method()

        # Setup serial and plot channels
        self.ser_channel_key, self.plot_channel_key = self.setup_channel_keys(
            ser_channel_key=ser_channel_key,
            **kwargs)

        # Storage paths: frames stream to segments in stream_dir, which are ingested into sqlite_path
        self.sqlite_path = os.path.abspath(sqlite_path)
        self.stream_dir = (os.path.abspath(stream_dir) if stream_dir
                           else os.path.splitext(self.sqlite_path)[0] + "_stream")
        self.storage_enabled = bool(start_stream_ingest)
        for other in list(_OPEN_MANAGERS.values()):
            if self.storage_enabled and other.storage_enabled and other.stream_dir == self.stream_dir:
                warnings.warn(f"closing the previous SensorManager that stored data through {self.stream_dir}",
                              RuntimeWarning, stacklevel=2)
                other.close()

        # Setup ring buffer, with a name unique to this SensorManager
        self.shm_name = shm_name or f"/sc_{os.getpid()}_{uuid.uuid4().hex[:8]}"
        self.ring_capacity = int(ring_capacity)
        self.ring, self.logical_shape = initialize_ring(ser_channel_key=ser_channel_key,
                                                        dtype=dtype,
                                                        shm_name=self.shm_name,
                                                        frames_capacity=self.ring_capacity,
                                                        data_mode=data_mode,
                                                        frame_shape=frame_shape)
        _track_shared_memory(self.shm_name)
        try:
            self._setup(commport, baudrate, rotate_frames, rotate_seconds, **kwargs)
        except BaseException:
            self._release()
            raise
        _OPEN_MANAGERS[id(self)] = self
        self._closed = False

    def _setup(self, commport, baudrate, rotate_frames, rotate_seconds, **kwargs):
        """ Create the shared settings, metrics, and (when storing data) the writer and ingester processes """
        # Setup target consumer params and enforce
        plot_target_fps = kwargs.get("plot_target_fps", 60.0)
        plot_catch_up_max = kwargs.get("plot_catchup_base_max", 2048)
        plot_catchup_boost = kwargs.get("plot_catchup_boost", 2.5)

        plot_target_fps = _coerce(plot_target_fps, 60.0)
        plot_catch_up_max = int(_coerce(plot_catch_up_max, 2048))
        plot_catchup_boost = _coerce(plot_catchup_boost, 2.5)

        # Setup static args dict
        self.static_args_dict = create_static_dict(ser_channel_key=self.ser_channel_key,
                                                   plot_channel_key=self.plot_channel_key,
                                                   commport=commport,
                                                   baudrate=baudrate,
                                                   shm_name=self.shm_name,
                                                   shape=self.logical_shape,
                                                   dtype=self.dtype,
                                                   ring_capacity=self.ring_capacity,
                                                   data_mode=self.data_mode,
                                                   frame_shape=self.logical_shape
                                                   )

        self.static_args_dict = update_static_dict(static_args_dict=self.static_args_dict,
                                                   plot_target_fps=plot_target_fps,
                                                   plot_catch_up_max=plot_catch_up_max,
                                                   plot_catchup_boost=plot_catchup_boost
                                                   )

        # Make shared proxies for metrics
        self._mp_manager = SyncManager()
        self._mp_manager.start(initializer=_exit_with_parent)
        self.writer_metrics_proxy = self._mp_manager.dict()
        self.plot_metrics_proxy = self._mp_manager.dict()
        self.ingest_metrics_proxy = self._mp_manager.dict()
        # Initialize proxies
        self.writer_metrics_proxy.update({"init": True})
        self.plot_metrics_proxy.update({"init": True})
        self.ingest_metrics_proxy.update({"init": True, "ingest_config_enabled": self.storage_enabled})

        # Make shared proxy for DSP
        self._plot_dsp = DSPManager()
        self._plot_dsp_version = 0

        self.plot_dsp_proxy = self._mp_manager.dict()
        self.plot_dsp_proxy.update({
            "version": 0,
            "queue": [],
            "modules": {},
        })

        # Signals to the worker processes
        self._acquire_stop = multiprocessing.Event()
        self._writer_stop = multiprocessing.Event()
        self._ingest_stop = multiprocessing.Event()
        self._seal_request = multiprocessing.Event()
        self._writer_ready = multiprocessing.Event()
        self._ingest_ready = multiprocessing.Event()
        self._acquire_workers = []
        self._plot_workers = []
        self._plot_managers = []
        self._stream_proc = None
        self._ingest_proc = None
        self.session = None

        if self.storage_enabled:
            from sensor_core.memory.stream_logger import dump_loop, new_session
            from sensor_core.memory.db_ingester import ingest_loop
            # Stored frames carry this session's identity and clock anchor (see strg_manager)
            self.session = new_session()
            self._stream_proc = Process(name="stream_writer", target=dump_loop,
                                        args=(self.stream_dir, self.shm_name, self.ring_capacity,
                                              self.logical_shape, self.dtype),
                                        kwargs={"data_mode": self.data_mode,
                                                "rotate_frames": int(rotate_frames),
                                                "rotate_seconds": float(rotate_seconds) if rotate_seconds else None,
                                                "metrics_proxy": self.writer_metrics_proxy,
                                                "stop_event": self._writer_stop,
                                                "seal_event": self._seal_request,
                                                "ready_event": self._writer_ready,
                                                "start_idx": 0,
                                                "channels": list(self.ser_channel_key),
                                                "session": self.session})
            self._ingest_proc = Process(name="stream_ingester", target=ingest_loop,
                                        args=(self.stream_dir, self.sqlite_path),
                                        kwargs={"metrics_proxy": self.ingest_metrics_proxy,
                                                "stop_event": self._ingest_stop,
                                                "ready_event": self._ingest_ready})
            self.start_process(self._stream_proc)
            self.start_process(self._ingest_proc)
            # Wait until both can accept data, so a worker that cannot start fails here, loudly
            self._wait_until_ready(self._stream_proc, self._writer_ready, "writer")
            self._wait_until_ready(self._ingest_proc, self._ingest_ready, "ingest")

    def _wait_until_ready(self, proc, ready, name, timeout: float = 120.0):
        deadline = time.monotonic() + timeout
        while not ready.wait(0.05):
            if not proc.is_alive():
                error = self.writer_metrics_proxy if name == "writer" else self.ingest_metrics_proxy
                raise RuntimeError(f"the stream {name} failed to start: {error.get(f'{name}_last_error')}")
            if time.monotonic() > deadline:
                raise TimeoutError(f"the stream {name} did not start within {timeout:.0f} s")

    @staticmethod
    def setup_channel_keys(ser_channel_key, **kwargs):
        """ Set up serial and plot channel keys
        :param ser_channel_key: serial channel key (list of names for serial channels)
        :param kwargs: can contain plot_channel_key kwarg, which we can use to set plot settings
        :return: ser_channel_key and plot_channel_key, lists of keys for serial and plot functions
        """
        if len(np.shape(ser_channel_key)) > 1:
            raise ValueError(f"serial channel key {ser_channel_key} \n"
                             f"must be a one-dimensional list")
        if "plot_channel_key" in kwargs:
            plot_channel_key = kwargs["plot_channel_key"]
        else:
            plot_channel_key = [ser_channel_key]

        plot_shape = np.shape(plot_channel_key)

        for key in np.reshape(plot_channel_key, (1, plot_shape[0] * plot_shape[1]))[0]:
            if key not in ser_channel_key:
                raise KeyError(f'plot_channel_key must include only keys within serial_channel_key')

        return ser_channel_key, plot_channel_key

    def update_data_process(self, save_data: bool = False, filepath: str = None,
                            virtual_ser_port: bool = False, func=None):
        """ Initialize dedicated process to update data

        :param save_data: deprecated; storage is set up when creating the SensorManager (start_stream_ingest=True)
        :param filepath: deprecated; the database is set when creating the SensorManager (sqlite_path)
        :param virtual_ser_port: boolean, if true data manager will not instantiate serial port. Will rely on
        user-defined custom function to generate simulated data
        :param func: optional custom function to handle serial data acquisition
        :return: pointer to process
        """
        if self._stopped:
            raise RuntimeError("this SensorManager has been stopped; create a new one to acquire again")
        if save_data or filepath is not None:
            warnings.warn("save_data and filepath are deprecated and store nothing; storage is set up when creating "
                          "the SensorManager, with start_stream_ingest=True and sqlite_path",
                          DeprecationWarning, stacklevel=2)
        if save_data and (filepath is not None):
            filetype = pathlib.Path(filepath).suffix
            if filetype != ".hdf5" and filetype != ".sqlite3":
                raise ValueError(f"filepath {filepath} is an invalid filetype {filetype}\n"
                                 f"filepaths should create .hdf5 or .sqlite3 files only")

        odm = DataManager(static_args_dict=self.static_args_dict,
                          save_data=save_data,
                          filepath=filepath,
                          virtual_ser_port=virtual_ser_port,
                          metrics_proxy=self.writer_metrics_proxy)

        if self.os_flag == 'win':
            p = Thread(name='update',
                       target=odm.online_update_data,
                       args=(func,),
                       kwargs={"stop_event": self._acquire_stop},
                       daemon=True)
        else:
            p = Process(name='update',
                        target=odm.online_update_data,
                        args=(func,),
                        kwargs={"stop_event": self._acquire_stop})
        self._acquire_workers.append(p)
        return p

    def create_plot(self):
        """ Create the live plot; display it with its .show() method

        The figure updates itself from the ring buffer while it is shown, so it needs no process of its own.
        Create it after starting acquisition: on Linux and macOS, worker processes are started by forking this
        process, which is safest before the plot initializes the GPU.
        :return: fastplotlib Figure
        """
        if self._stopped:
            raise RuntimeError("this SensorManager has been stopped; create a new one to plot again")
        from sensor_core.plot import PlotManager

        pm = PlotManager(static_args_dict=self.static_args_dict,
                         metrics_proxy=self.plot_metrics_proxy,
                         plot_dsp_proxy=self.plot_dsp_proxy, )
        self._plot_managers.append(pm)
        return pm.fig

    def setup_plotting_process(self):
        """ Deprecated: use create_plot(), which returns the figure
        :return: pointer to a process (not needed; the figure updates itself while shown) and plot object
        """
        warnings.warn("setup_plotting_process() is deprecated; use create_plot(), which returns the figure. "
                      "The figure updates itself while it is shown, so no plotting process is needed.",
                      DeprecationWarning, stacklevel=2)
        fig = self.create_plot()
        pm = self._plot_managers[-1]
        if self.os_flag == 'win':
            p = Thread(name='plot',
                       target=pm.online_plot_data,
                       daemon=True)
        else:
            p = Process(name='plot',
                        target=pm.online_plot_data)
        self._plot_workers.append(p)
        return p, fig

    def start_process(self, process):
        """ Function to start given process, and ensure safe operability with windows

        :param process: process object to start
        """
        if self.os_flag == 'win':
            freeze_support()
            process.start()
        else:
            process.start()

    def flush(self, timeout: float = 30.0):
        """ Wait until every frame published so far is stored in the SQLite database

        Acquisition keeps running. Raises TimeoutError if storage does not catch up within timeout seconds.
        """
        if not self.storage_enabled:
            raise RuntimeError("storage is off; create the SensorManager with start_stream_ingest=True")
        if self._stopped:
            return  # stop() already stored everything
        target = self.ring.write_idx
        seals = self.writer_metrics_proxy.get("writer_seal_count", 0)
        rejected = self.ingest_metrics_proxy.get("ingest_segments_rejected", 0)
        self._seal_request.set()
        deadline = time.monotonic() + timeout

        def wait_for(done, worker, name):
            while not done():
                if not worker.is_alive():
                    raise RuntimeError(f"the stream {name} stopped: {self.get_metrics()[name].get(f'{name}_last_error')}")
                if time.monotonic() > deadline:
                    raise TimeoutError(f"flush timed out waiting for the stream {name}; see get_metrics()")
                time.sleep(0.02)

        wait_for(lambda: (self.writer_metrics_proxy.get("writer_seal_count", 0) > seals
                          and self.writer_metrics_proxy.get("writer_seal_idx", -1) >= target),
                 self._stream_proc, "writer")
        sealed = self.writer_metrics_proxy.get("writer_sealed_seq", 0)
        wait_for(lambda: self.ingest_metrics_proxy.get("ingest_last_seq", 0) >= sealed,
                 self._ingest_proc, "ingest")
        if self.ingest_metrics_proxy.get("ingest_segments_rejected", 0) > rejected:
            raise RuntimeError(f"a stream segment could not be stored: {self.ingest_metrics_proxy.get('ingest_last_error')}")

    def stop(self, timeout: float = 30.0):
        """ Stop acquisition and plotting, then store everything acquired so far

        Workers stop in order, so nothing in flight is lost: acquisition, the stream writer (which writes
        the rest of the ring and seals its last segment), then the ingester (which stores every segment).
        Safe to call more than once.
        """
        if self._stopped or self._closed:
            return
        self._stopped = True
        self._acquire_stop.set()
        for worker in self._acquire_workers:
            _join(worker, timeout)
        for pm in self._plot_managers:
            pm.stop()
        for worker in self._plot_workers:
            _join(worker, timeout)
        if self._stream_proc is not None:
            self._writer_stop.set()
            _join(self._stream_proc, timeout)
        if self._ingest_proc is not None:
            self._ingest_stop.set()
            _join(self._ingest_proc, timeout)
        try:
            self._final_metrics = self.get_metrics()
        except Exception:
            pass

    def close(self, timeout: float = 30.0):
        """ Stop everything (see stop()), then release the shared memory and helper processes

        Safe to call more than once; also called automatically when the interpreter exits.
        """
        if self._closed:
            return
        try:
            self.stop(timeout)
        finally:
            self._release()

    def _release(self):
        self._closed = True
        _OPEN_MANAGERS.pop(id(self), None)
        manager = getattr(self, "_mp_manager", None)
        if manager is not None:
            try:
                manager.shutdown()
            except Exception:
                pass
        self._acquire_workers = []
        self._plot_workers = []
        if getattr(self, "ring", None) is not None:
            self.ring = None
            unlink_ring(self.shm_name)
            _untrack_shared_memory(self.shm_name)

    @property
    def closed(self) -> bool:
        """True once close() has run"""
        return self._closed

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()

    def get_metrics(self) -> dict:
        """Return a combined metrics snapshot (the final one once the SensorManager is closed)."""
        if self._closed:
            return getattr(self, "_final_metrics", {"writer": {}, "plot": {}, "ingest": {}})
        metrics = {
            "writer": dict(self.writer_metrics_proxy),
            "plot": dict(self.plot_metrics_proxy),
            "ingest": dict(self.ingest_metrics_proxy),
        }
        # a worker that died cannot report it, so check it here
        for name, proc in (("writer", self._stream_proc), ("ingest", self._ingest_proc)):
            if proc is not None and not proc.is_alive() and not self._stopped:
                metrics[name][f"{name}_alive"] = False
        return metrics

    def force_seal_now(self):
        """Ask the writer to seal the active stream segment now, so the ingester can store it."""
        self._seal_request.set()

    def debug_status(self) -> dict:
        return {
            "writer_proc": {
                "pid": getattr(self._stream_proc, "pid", None),
                "alive": (self._stream_proc.is_alive() if self._stream_proc else False),
            },
            "ingest_proc": {
                "pid": getattr(self._ingest_proc, "pid", None),
                "alive": (self._ingest_proc.is_alive() if self._ingest_proc else False),
            },
            "paths": {
                "stream_dir": self.stream_dir,
                "sqlite": self.sqlite_path,
            },
        }

    def _publish_plot_dsp_cfg(self):
        self._plot_dsp_version += 1
        self.plot_dsp_proxy["version"] = int(self._plot_dsp_version)
        self.plot_dsp_proxy["queue"] = list(self._plot_dsp.dsp_modules_queue)
        self.plot_dsp_proxy["modules"] = dict(self._plot_dsp.dsp_modules)

    # UI entrypoints
    def add_plot_dsp_module(self, name: str, target_algo: str, **kwargs):
        """
        Add a visualization-only DSP module. Does not affect stored data.
        Example:
          add_plot_dsp_module("ma1", "moving_average_filter", window_size=16, pad="percentile")
          add_plot_dsp_module("bp1", "butterworth_filter", order=2, min_frq=1, max_frq=20, fs=200)
        """
        self._plot_dsp.add_dsp_module(name, target_algo, **kwargs)
        self._publish_plot_dsp_cfg()

    def remove_plot_dsp_module(self, name: str):
        self._plot_dsp.remove_dsp_module(name)
        self._publish_plot_dsp_cfg()

    def clear_plot_dsp_modules(self):
        self._plot_dsp.dsp_modules.clear()
        self._plot_dsp.dsp_modules_queue.clear()
        self._publish_plot_dsp_cfg()

    def set_plot_dsp_order(self, new_queue):
        new_queue = list(new_queue)
        if set(new_queue) != set(self._plot_dsp.dsp_modules_queue):
            raise ValueError("new_queue must contain exactly the existing DSP module names.")
        self._plot_dsp.dsp_modules_queue = new_queue
        self._publish_plot_dsp_cfg()

    def get_plot_dsp_cfg(self) -> dict:
        return {
            "version": int(self._plot_dsp_version),
            "queue": list(self._plot_dsp.dsp_modules_queue),
            "modules": dict(self._plot_dsp.dsp_modules),
        }